### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by fleli723** [fleli723/sprint2#1]
- [x] **Correct deficiencies from sprint1**
- [ ] **Handle backdoors with going to result pages (using session issets) (surveyList - Filip)**
- [x] PHP - show alert for no search catcher as an h2 tag
- [x] HTMLCSS - Username and Password fields for login ("type = password" for input) (topNavBar)
- [x] HTMLCSS - Display album's store page link in table
- [x] HTMLCSS - Welcome <first name> message for logged in users
- [x] HTMLCSS - Logout button for users logged in - should not display if user isnt logged in
- [ ] HTMLCSS - change login and search button IDs
- [ ] DB - Fix bad Elvis link
- [x] DB - Store passwords in DB / not in plaintext
- [x] DB - Create an admin role and user role
- [x] DB - Create two users, one with admin one with user role assigned
- [x] DB - Users should be able to exist multiple roles
- [x] DB - Add column to album database with links to store page to buy album
- [x] DB - **Single query for authentication of users (move queries to web services)**
- [x] DB - If getting data from DB, only use dbEsc
- [x] DB - Sanitize then dbEsc if inputting to DB
- [x] PHP - Switch to have sanitization before db escape
- [x] PHP - Mask passwords using password_hash() and password_verify()
- [x] PHP - Admin user roles should be able to view survey page results in a table format
- [x] PHP - Use of session to recognize if a user is logged in (isset)
- [x] PHP - Logout functionality which clears session variable for user
- [x] PHP - Create function to validate the user with error message if incorrect credentials
- [x] PHP - Depending if user is logged in or not, show login fields and login button or welcome with logout button (isset session)
- [x] PHP - Find a way to clear notice of email on surveyResult.php
- [ ] JS - Change alert messages to a friendly manner error messages (login) (no alert messages) (searchResult - Corbin)
- [ ] JS - Use whenever possible on forms, so user experience is the same as on different sites
- [ ] JS - Add js validation to login - Corbin
- [ ] Validate HTML and CSS
